name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish .NET Core Project
        # Publish to the 'release' folder
        run: dotnet publish SmartOnFhirApp/SmartOnFhirApp.csproj -c Release -o release --nologo

      # Automatically update base-tag in index.html to match the repository name
      # Example: "MyUser/MyRepo" -> "/MyRepo/"
      - name: Configure base tag
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          if [[ "$REPO_NAME" == *".github.io" ]]; then
            echo "Repository is a User/Organization User Page. Using root base path."
            BASE_HREF="/"
          else
            echo "Repository is a Project Page. Using subfolder base path."
            BASE_HREF="/$REPO_NAME/"
          fi
          
          echo "Setting base href to: $BASE_HREF"
          # Use different delimiter for sed to avoid escaping slashes
          sed -i "s|<base href=\"/\" />|<base href=\"$BASE_HREF\" />|g" release/wwwroot/index.html
          
          if [ -f release/wwwroot/404.html ]; then
            sed -i "s|<base href=\"/\" />|<base href=\"$BASE_HREF\" />|g" release/wwwroot/404.html
          fi

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit and Push to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
